# -*- coding: utf-8 -*-
"""Canada income LR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QZFiXP7-HzwvXmLIx_h2Mb5EeiGfGcDa
"""

import pandas as pd
from sklearn.linear_model import LinearRegression

"""loading data set"""

df = pd.read_csv('/content/canada_per_capita_income.csv')

X = df[['year']]
y = df['per capita income (US$)']

"""Train the model"""

model = LinearRegression()
model.fit(X, y)

"""Predict for 2020"""

prediction_2020 = model.predict([[2020]])

print("Predicted per capita income for 2020:")
print(prediction_2020[0])