# -*- coding: utf-8 -*-
"""Linear Regression.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WaeRSa3T6gUu1EJI5EQJbqJRhpK6N7GG
"""

import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

"""Imported the library"""

df = pd.read_csv('homeprices.csv')
df

"""here is data set"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area')
plt.ylabel('price')
plt.scatter(df.area,df.price,color='red',marker='+')

reg = linear_model.LinearRegression()
reg.fit(df[['area']],df.price)

"""Create linear regression object and fit the data"""

reg.predict([[3300]])

"""predicting price based on area"""

reg.coef_

"""To show m(slope) value"""

reg.intercept_

"""To show value of b"""

reg.predict([[5000]])